/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package com.yunpayroll.formular;

public interface ParserTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTSTATEMENT = 1;
  public int JJTVALUEOFSUBTABLE = 2;
  public int JJTPAIRS = 3;
  public int JJTPAIR = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTEXPRESSIONLISTITEM = 6;
  public int JJTEXPRESSION = 7;
  public int JJTOREXPRESSION = 8;
  public int JJTANDEXPRESSION = 9;
  public int JJTREGULARCONDITION = 10;
  public int JJTSIMPLEEXPRESSIONLIST = 11;
  public int JJTSIMPLEEXPRESSIONLISTATLEASTTWOITEMS = 12;
  public int JJTCOMPARISONITEM = 13;
  public int JJTSIMPLEEXPRESSION = 14;
  public int JJTCONCATEXPRESSION = 15;
  public int JJTBITWISEANDOR = 16;
  public int JJTADDITIVEEXPRESSION = 17;
  public int JJTMULTIPLICATIVEEXPRESSION = 18;
  public int JJTBITWISEXOR = 19;
  public int JJTPRIMARYEXPRESSION = 20;
  public int JJTCOLUMN = 21;
  public int JJTCOLDATATYPE = 22;
  public int JJTDATETIMELITERALEXPRESSION = 23;
  public int JJTCASTEXPRESSION = 24;
  public int JJTCASEWHENEXPRESSION = 25;
  public int JJTWHENTHENSEARCHCONDITION = 26;
  public int JJTWHENTHENVALUE = 27;
  public int JJTFUNCTION = 28;
  public int JJTRELOBJECTNAME = 29;
  public int JJTPKOBJECTNAME = 30;
  public int JJTCONDITION = 31;
  public int JJTSQLCONDITION = 32;
  public int JJTLIKEEXPRESSION = 33;
  public int JJTISNULLEXPRESSION = 34;
  public int JJTRELOBJECTNAMEEXT = 35;


  public String[] jjtNodeName = {
    "error_skipto",
    "Statement",
    "ValueOfSubtable",
    "Pairs",
    "Pair",
    "Identifier",
    "ExpressionListItem",
    "Expression",
    "OrExpression",
    "AndExpression",
    "RegularCondition",
    "SimpleExpressionList",
    "SimpleExpressionListAtLeastTwoItems",
    "ComparisonItem",
    "SimpleExpression",
    "ConcatExpression",
    "BitwiseAndOr",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "BitwiseXor",
    "PrimaryExpression",
    "Column",
    "ColDataType",
    "DateTimeLiteralExpression",
    "CastExpression",
    "CaseWhenExpression",
    "WhenThenSearchCondition",
    "WhenThenValue",
    "Function",
    "RelObjectName",
    "PKObjectName",
    "Condition",
    "SQLCondition",
    "LikeExpression",
    "IsNullExpression",
    "RelObjectNameExt",
  };
}
/* JavaCC - OriginalChecksum=2291072b83365d2fb7939938a8a6c215 (do not edit this line) */
